board/board/urls.py
from django.contrib import admin
from django.urls import path, include
import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

board/core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import board, api



app_name = 'core'


urlpatterns = [
    path('',                                     board.board, name='all'),
    path('page/<int:page>',                      board.board, name='all'),
    path('tag/<slug:tag_name>/',                 board.board, name='by_tag'),
    path('tag/<slug:tag_name>/page/<int:page>',  board.board, name='by_tag'),

    path('catalog',                                     board.catalog, name='catalog_all'),
    path('catalog/<int:page>',                          board.catalog, name='catalog_all'),
    path('catalog/tag/<slug:tag_name>/',                board.catalog, name='catalog_tag'),
    path('catalog/tag/<slug:tag_name>/page/<int:page>', board.catalog, name='catalog_tag'),

    path('thread/<int:number>', board.thread, name='thread'),

    path('find_posts_by_ip', board.find_posts_by_ip, name='find_posts_by_ip'),
    path('api/mod_del_post', api.mod_del_post,       name='api_mod_del_post'),
    path('api/ban_user',     api.ban_user,           name='api_ban_user'),
    path('api/render_post',  api.render_post,        name='api_render_post'),
    path('api/del_post',     api.del_post,           name='api_del_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/core/models.py
import os
import uuid
import hashlib
from django.db import models
from django.utils import timezone
import django.urls
from . import config
from .abstracts import markup


class Banned(BaseException):
    def __init__(self, ban):
        super().__init__()
        self.ban = ban


class WrongPassword(BaseException):
    pass


class ContentMissing(BaseException):
    pass


class Ban(models.Model):
    ip = models.GenericIPAddressField(primary_key=True)
    reason = models.TextField()
    expires_at = models.DateTimeField(db_index=True)

    def __str__(self):
        return f'{self.ip}: {self.reason}'

    @staticmethod
    def create_with_duration(ip, reason, duration):
        return Ban(ip=ip, reason=reason, expires_at=timezone.now() + duration)

    @staticmethod
    def check_ip(ip, now):
        try:
            ban = Ban.objects.get(ip=ip)
            if ban.expires_at > now:
                raise Banned(ban)
        except Ban.DoesNotExist:
            pass


class Tag(models.Model):
    name = models.CharField(max_length=10, primary_key=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return django.urls.reverse('core:by_tag', args=(self.name,))

    def get_threads(self):
        return self.threads_with_tag


def _get_image_path(post, filename):
    _, ext = os.path.splitext(filename)
    return str(uuid.uuid1()) + ext


class Post(models.Model):
    number = models.AutoField(primary_key=True)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to=_get_image_path,
                              height_field='image_width',
                              width_field='image_height',
                              null=True)
    image_height = models.IntegerField(null=True)
    image_width = models.IntegerField(null=True)
    timestamp = models.DateTimeField()
    bumptime = models.DateTimeField(null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='threads_with_tag')
    ip = models.GenericIPAddressField(db_index=True)
    password_sha256 = models.CharField(max_length=64, null=True)

    def __str__(self):
        return f'#{self.number}: {self.text[:50]}'

    def get_absolute_url(self):
        if self.parent is not None:
            thread_url = django.urls.reverse('core:thread', args=(self.parent.number,))
            return f'{thread_url}#i{self.number}'
        else:
            return django.urls.reverse('core:thread', args=(self.number,))

    def get_anchored_url(self):
        thread_number = self.parent.number if self.parent is not None else self.number
        thread_url = django.urls.reverse('core:thread', args=(thread_number,))
        return f'{thread_url}#i{self.number}'

    @staticmethod
    def get_all_threads():
        return Post.objects.filter(parent=None)

    @staticmethod
    def create_thread(text, image, password, tags, ip):
        if not image:
            raise ContentMissing('image is required when creating a thread')
        now = timezone.now()
        Ban.check_ip(ip, now)
        thread = Post(
            text=_process_markup(text),
            image=image,
            timestamp=now,
            bumptime=now,
            parent=None,
            ip=ip,
            password_sha256=_get_password_sha256(password))
        thread.save()
        thread.tags.set(tags)
        return thread

    def get_comments(self):
        return Post.objects.filter(parent=self)

    def bumpable(self):
        return self.get_comments().count() < config.BUMP_LIMIT

    def add_comment(self, text, image, password, sage, ip):
        if not text and not image:
            raise ContentMissing('either a text or an image is required')
        now = timezone.now()
        Ban.check_ip(ip, now)
        comment = Post(
            text=_process_markup(text),
            image=image,
            timestamp=now,
            bumptime=None if sage else now,
            parent=self,
            ip=ip,
            password_sha256=_get_password_sha256(password))

        if not sage and self.bumpable():
            self.bumptime = now
            self.save()

        comment.save()
        return comment

    def delete_with_password(self, password):
        if self.password_sha256 is None:
            raise WrongPassword()
        if _get_password_sha256(password) != self.password_sha256:
            raise WrongPassword()
        self.delete()


def with_comment_counts(threads):
    """
    Yields `(thread, n_comments)` tuples.
    """
    query = Post.objects.filter(parent__in=threads)
    query = query.values('parent')
    query = query.annotate(ncomments=models.Count('*'))

    ncomments_by_number = {row['parent']: row['ncomments'] for row in query}

    for thread in threads:
        yield thread, ncomments_by_number.get(thread.number, 0)


def with_comment_previews(threads, nlast):
    """
    Yields `(thread, n_omitted_comments, preview_comments)` tuples.
    """
    for thread, ncomments in with_comment_counts(threads):
        preview = list(reversed(Post.objects.filter(parent=thread).order_by('-number')[:nlast]))
        yield thread, max(0, ncomments - len(preview)), preview


def _process_markup(text):
    nreplies = 0

    MAX_POSTNUM = (1 << 31) - 1

    def make_reply(postnum, content):
        nonlocal nreplies
        if nreplies >= config.MAX_POST_REPLIES:
            return content
        if postnum > MAX_POSTNUM:
            return content
        try:
            post = Post.objects.get(number=postnum)
        except Post.DoesNotExist:
            return content
        nreplies += 1
        return f'<a href="{post.get_anchored_url()}" class="toto-link" data-to="{postnum}">{content}</a>'

    return markup.process(text, make_reply)


def _get_password_sha256(password):
    if not password:
        return None
    return hashlib.sha256(password.encode()).hexdigest()

board/core/forms.py
from django import forms
from . import models


_MAX_PASS_LENGTH = 32


class ThreadForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, required=False)
    password = forms.CharField(max_length=_MAX_PASS_LENGTH,
                               widget=forms.PasswordInput(),
                               required=False)
    tags = forms.ModelMultipleChoiceField(
        queryset=models.Tag.objects.order_by('name'),
        required=False)
    image = forms.ImageField(required=False)


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, required=False)
    sage = forms.BooleanField(required=False)
    password = forms.CharField(max_length=_MAX_PASS_LENGTH,
                               widget=forms.PasswordInput(),
                               required=False)
    image = forms.ImageField(required=False)

board/core/views/api.py
import datetime
from django.shortcuts import render
from django.http import (
    Http404,
    HttpResponseBadRequest,
    HttpResponseNotAllowed,
    JsonResponse,
)
from django.db.models import prefetch_related_objects
from .utils import mod_only
from .. import models
from .. import config
from ..abstracts.zero_based_paginator import ZeroBasedPaginator


@mod_only
def mod_del_post(request):
    if request.method == 'POST':
        try:
            postnum = int(request.POST['postnum'])
            all_with_same_ip = bool(int(request.POST['all_with_same_ip']))
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

        try:
            post = models.Post.objects.get(number=postnum)
        except models.Post.DoesNotExist:
            return JsonResponse({'ok': False, 'error': 'post not found'})

        if all_with_same_ip:
            models.Post.objects.filter(ip=post.ip).delete()
        else:
            post.delete()

        return JsonResponse({'ok': True})

    return HttpResponseNotAllowed(['POST'])


@mod_only
def ban_user(request):
    if request.method == 'POST':
        try:
            ip = request.POST['ip']
            reason = request.POST['reason']
            duration = int(request.POST['duration'])
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

        ban = models.Ban.create_with_duration(
            ip=ip,
            reason=reason,
            duration=datetime.timedelta(seconds=duration))
        ban.save()

        return JsonResponse({'ok': True})

    return HttpResponseNotAllowed(['POST'])


def render_post(request):
    if request.method == 'GET':
        try:
            postnum = int(request.GET['postnum'])
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

        try:
            post = models.Post.objects.get(number=postnum)
        except models.Post.DoesNotExist:
            raise Http404()

        return render(request, 'post.html', {
            'post': post,
            'has_tags': False,
            'open_link': False,
        })

    return HttpResponseNotAllowed(['GET'])


def del_post(request):
    if request.method == 'POST':
        try:
            postnum = int(request.POST['postnum'])
            password = request.POST['password']
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

        try:
            post = models.Post.objects.get(number=postnum)
        except models.Post.DoesNotExist:
            raise Http404()

        try:
            post.delete_with_password(password)
        except models.WrongPassword:
            return JsonResponse({'ok': False, 'error': 'wrong password'})
        else:
            return JsonResponse({'ok': True})

    return HttpResponseNotAllowed(['POST'])

board/core/views/board.py
from django.shortcuts import render
from django.http import (
    Http404,
    HttpResponseRedirect,
    HttpResponseBadRequest,
)
from django.db.models import prefetch_related_objects
from .utils import get_ip, mod_only
from .. import forms
from .. import models
from .. import config
from ..abstracts.zero_based_paginator import ZeroBasedPaginator


def board(request, tag_name=None, page_index=0):
    if request.method == 'POST':
        form = forms.ThreadForm(request.POST, request.FILES)

        if form.is_valid():
            try:
                thread = models.Post.create_thread(
                    text=form.cleaned_data['text'],
                    image=form.cleaned_data['image'],
                    password=form.cleaned_data['password'],
                    tags=form.cleaned_data['tags'],
                    ip=get_ip(request))
            except models.Banned as ex:
                return render(request, 'banned.html', {
                    'ban': ex.ban,
                })
            return HttpResponseRedirect(thread.get_absolute_url())
    else:
        form = forms.ThreadForm()

    if tag_name is not None:
        try:
            threads = models.Tag.objects.get(name=tag_name).get_threads()
        except models.Tag.DoesNotExist:
            raise Http404()
    else:
        threads = models.Post.get_all_threads()

    threads = threads.order_by('-bumptime')
    page = ZeroBasedPaginator(threads, config.THREADS_PER_PAGE).page(page_index)

    prefetch_related_objects(page.object_list, 'tags')

    return render(request, 'board.html', {
        'tag_name': tag_name,
        'data':     models.with_comment_previews(page.object_list, config.PREVIEW_COMMENTS),
        'page':     page,
        'form':     form,
    })


def catalog(request, tag_name=None, page_index=0):
    if request.method == 'GET':
        if tag_name is not None:
            try:
                threads = models.Tag.objects.get(name=tag_name).get_threads()
            except models.Tag.DoesNotExist:
                raise Http404()
        else:
            threads = models.Post.get_all_threads()

        threads = threads.order_by('-bumptime')

        page = ZeroBasedPaginator(threads, config.CATALOG_SIZE).page(page_index)

        prefetch_related_objects(page.object_list, 'tags')

        return render(request, 'catalog.html', {
            'tag_name': tag_name,
            'data':     models.with_comment_counts(page.object_list),
            'page':     page,
        })

    return HttpResponseNotAllowed(['GET'])


def thread(request, number):
    try:
        thread = models.Post.objects.get(number=number)
    except models.Post.DoesNotExist:
        raise Http404()

    if thread.parent is not None:
        raise Http404()

    if request.method == 'POST':
        form = forms.CommentForm(request.POST, request.FILES)

        if form.is_valid():
            try:
                comment = thread.add_comment(
                    text=form.cleaned_data['text'],
                    image=form.cleaned_data['image'],
                    password=form.cleaned_data['password'],
                    sage=form.cleaned_data['sage'],
                    ip=get_ip(request))
            except models.Banned as ex:
                return render(request, 'banned.html', {
                    'ban': ex.ban,
                })
            return HttpResponseRedirect(comment.get_absolute_url())
    else:
        form = forms.CommentForm()

    return render(request, 'thread.html', {
        'thread':   thread,
        'comments': thread.get_comments().order_by('number'),
        'form':     form,
    })


@mod_only
def find_posts_by_ip(request):
    if request.method == 'GET':
        try:
            ip = request.GET['ip']
            page_index = int(request.GET.get('page', '0'))
        except (KeyError, ValueError):
            return HttpResponseBadRequest()
        if page_index < 0:
            return HttpResponseBadRequest()

        page = ZeroBasedPaginator(
                models.Post.objects.filter(ip=ip).order_by('number'),
                config.POSTS_BY_IP_PER_PAGE
            ).page(page_index)

        prefetch_related_objects(page.object_list, 'tags')

        return render(request, 'find-posts-by-ip.html', {
            'ip':   ip,
            'page': page,
        })

    return HttpResponseNotAllowed(['GET'])

board/core/views/utils.py
from django.http import HttpResponseForbidden


def mod_only(func):
    def wrapper(request, *args, **kwargs):
        if not request.user.has_perm('core.change_post'):
            return HttpResponseForbidden()
        return func(request, *args, **kwargs)
    return wrapper


def get_ip(request):
    return request.META.get('REMOTE_ADDR')

board/core/templates/banned.html
{% extends "base.html" %}

{% block title %}
    You have been banned!
{% endblock %}

{% block content %}
    <div id="global-cont">
        <b>You have been banned!</b>
        <br/>
        <b>Reason</b>: {{ ban.reason }}.
        <br/>
        <b>Your ban expires at</b>: {{ ban.expires_at }}.
    </div>
{% endblock %}

board/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/style.css">
    <script src="/static/lib.js"></script>
    <script>
        var CFG_IS_MOD = "{{ is_mod }}" === "True";
        var CFG_PATHS = {
            find_posts_by_ip:  "{% url 'core:find_posts_by_ip' %}",
            api_mod_del_post:  "{% url 'core:api_mod_del_post' %}",
            api_ban_user:      "{% url 'core:api_ban_user' %}",

            api_render_post:   "{% url 'core:api_render_post' %}",
            api_del_post:      "{% url 'core:api_del_post' %}",
        };
    </script>
</head>
<body>
    <header id="header">
        <a class="tag-link" href="{% url 'core:all' %}">All threads</a>
        | <a href="javascript:window.history.back()" class="tag-link">Back</a>
        | Tags:
        {% for tag in existing_tags %}
            <a class="tag-link" href="{{ tag.get_absolute_url }}">~{{ tag.name }}</a>
        {% endfor %}

        {% if is_mod %}
            <span class="user-panel">
                Logged in as <a class="user-name" href="{% url 'admin:index' %}">{{ user.username }}</a>
            </span>
        {% endif %}
    </header>

    <h1>{% block header_text %}{% endblock %}</h1>

    {% block content %}{% endblock %}
</body>
</html>

board/core/templates/board.html
{% extends "base.html" %}

{% block title %}
    {% if tag_name %}
        ~{{ tag_name }}
    {% else %}
        Board
    {% endif %}
{% endblock %}

{% block header_text %}
    {% if tag_name %}
        ~{{ tag_name }}
    {% else %}
        All threads
    {% endif %}
{% endblock %}

{% block content %}

    <div id="global-cont">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <table>{{ form }}</table>
            <input type="submit" value="New thread"/>
        </form>
        <br/>

        {% for thread, nomitted, comments in data %}
            {% include "original-post.html" with open_link=True %}

            {% if nomitted %}
                <span class="light-msg">Omitted {{ nomitted }} comment(s).</span>
            {% endif %}

            {% for comment in comments %}
                {% include "comment.html" %}
            {% endfor %}
        {% empty %}
            <span class="light-msg">No threads yet.</span>
        {% endfor %}
    </div>

    Pages:
    {% for page_num in page.paginator.page_range %}
        {% spaceless %}
        <span class="page-number">
            {% if page_num == page.number %}
                <span>{{ page_num }}</span>
            {% else %}
                {% if tag_name %}
                    <a class="page-link" href="{% url 'core:by_tag' tag_name page_num %}">{{ page_num }}</a>
                {% else %}
                    <a class="page-link" href="{% url 'core:all' page_num %}"            >{{ page_num }}</a>
                {% endif %}
            {% endif %}
        </span>
        {% endspaceless %}
    {% endfor %}

{% endblock %}

board/core/templates/catalog.html
{% extends "base.html" %}

{% block title %}
    {% if tag_name %}
        Catalog: ~{{ tag_name }}
    {% else %}
        Catalog
    {% endif %}
{% endblock %}

{% block header_text %}
    {% if tag_name %}
        Catalog: ~{{ tag_name }}
    {% else %}
        Catalog
    {% endif %}
{% endblock %}

{% block content %}

    <div id="global-cont">
        {% for thread, ncomments in data %}
            <div class="catalog-thread">
                <div class="post-header">
                    <b>#{{ thread.number }}</b>
                    <a class="open-thread-link" href="{{ thread.get_absolute_url }}">Open</a>
                </div>
                <!-- TODO: image -->
                <span class="light-msg">{{ ncomments }} comment(s).</span>
            </div>
        {% empty %}
            <span class="light-msg">No threads yet.</span>
        {% endfor %}
    </div>

    Pages:
    {% for page_num in page.paginator.page_range %}
        {% spaceless %}
        <span class="page-number">
            {% if page_num == page.number %}
                <span>{{ page_num }}</span>
            {% else %}
                {% if tag_name %}
                    <a class="page-link" href="{% url 'core:catalog_tag' tag_name page_num %}">{{ page_num }}</a>
                {% else %}
                    <a class="page-link" href="{% url 'core:catalog_all' page_num %}"         >{{ page_num }}</a>
                {% endif %}
            {% endif %}
        </span>
        {% endspaceless %}
    {% endfor %}

{% endblock %}

board/core/templates/comment.html
<article id="i{{ comment.number }}" class="post comment">
    {% include "post.html" with post=comment open_link=False has_tags=False %}
</article>

board/core/templates/find-posts-by-ip.html
{% extends "base.html" %}

{% block title %}
    Find posts by IP
{% endblock %}

{% block header_text %}
    Posts with IP {{ ip }}
{% endblock %}

{% block content %}
    <div id="global-cont">
        {% for post in page.object_list %}
            {% if post.parent %}
                {% include "comment.html" with comment=post %}
            {% else %}
                {% include "original-post.html" with thread=post open_link=True %}
            {% endif %}
        {% endfor %}
    </div>

    Pages:
    {% for page_num in page.paginator.page_range %}
        {% spaceless %}
        <span class="page-number">
            {% if page_num == page.number %}
                <span>{{ page_num }}</span>
            {% else %}
                <a class="page-link" href="{% url 'core:find_posts_by_ip' %}?ip={{ ip }}&page={{ page_num }}">{{ page_num }}</a>
            {% endif %}
        </span>
        {% endspaceless %}
    {% endfor %}
{% endblock %}

board/core/templates/original-post.html
<article id="i{{ thread.number }}" class="post original-post">
    {% include "post.html" with post=thread tags=thread.tags.all has_tags=True %}
</article>

board/core/templates/post.html
<div class="post-header">
    <a href="javascript:void(0)" class="post-time" data-number="{{ post.number }}" data-link="{{ post.get_anchored_url }}"
       {% if is_mod %} data-ip="{{ post.ip }}" {% endif %}
    >{{ post.timestamp }}</a>

    {% if has_tags %}
        {% for tag in tags %}
            ~{{ tag.name }}
        {% endfor %}
    {% endif %}

    <a href="javascript:insert_reply({{ post.number }})" class="post-num">#{{ post.number }}</a>

    {% if open_link %}
        <a class="open-thread-link" href="{{ post.get_absolute_url }}">Open</a>
    {% endif %}
</div>

{% if post.image %}
    <div class="post-image-descr">
        File: <a href="{{ post.image.url }}">{{ post.image.name | truncatechars:15 }}</a>,
        {{ post.image_width }}×{{ post.image_height }}
    </div>
    <div class="post-image">
        <img src="{{ post.image.url }}" style="height: 150px; width: 150px;"/>
    </div>
{% endif %}

<div class="post-text">
    {{ post.text | safe }}
</div>

board/core/templates/thread.html
{% extends "base.html" %}

{% block title %}
    Thread {{ thread.number }}
{% endblock %}

{% block content %}
    <div id="global-cont">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <table>{{ form }}</table>
            <input type="submit" value="Post"/>
        </form>
        <br/>

        {% include "original-post.html" with open_link=False %}
        {% for comment in comments %}
            {% include "comment.html" %}
        {% endfor %}
    </div>
{% endblock %}